source 'https://rubygems.org'

gem 'rails', github: 'rails/rails'

gem 'pg', '~> 0.18'
gem 'puma'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers'
gem 'kaminari'
gem 'faker'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'bullet', github: 'flyerhzm/bullet'
  gem 'byebug' # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'rspec-rails'
end

group :test do
  gem 'json_matchers'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'simplecov', require: false
end

group :development do
  gem 'spring' # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
